openapi: 3.0.1
info:
  description: uim mp api
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Uim mp api
  version: 1.0.0
servers:
- url: http://localhost:58200/app/wechatmp/proxy/v1
tags:
- description: uim wechat media platform api
  name: 微信公众号api
paths:
  /sendMessage:
    post:
      description: 发送客服消息
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
          description: successful operation
      summary: 发送客服消息
      tags:
      - wpub
      x-codegen-request-body-name: body
  /listUser:
    post:
      description: 获取所有关注用户
      operationId: listUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListUserReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: successful operation
      summary: 获取所有关注用户
      tags:
      - wpub
      x-codegen-request-body-name: body
  /userDetail:
    post:
      description: 获取单个关注用户信息
      operationId: userDetail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDetailReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: successful operation
      summary: 获取单个关注用户信息
      tags:
      - wpub
      x-codegen-request-body-name: body
  /updateUserTag:
    post:
      description: 更新用户标签
      operationId: updateUserTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserTagReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
          description: successful operation
      summary: 更新用户标签
      tags:
      - wpub
      x-codegen-request-body-name: body
  /updateUserRemark:
    post:
      description: 更新用户备注
      operationId: updateUserRemark
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRemarkReq'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
          description: successful operation
      summary: 更新用户备注
      tags:
      - wpub
      x-codegen-request-body-name: body
components:
  schemas:
    SendMessageReq:
      example:
        toUser: toUser
        voice:
          mediaURL: mediaURL
          mediaId: mediaId
        image:
          mediaURL: mediaURL
          mediaId: mediaId
        msgType: msgType
        music:
          thumbMediaURL: thumbMediaURL
          thumbMediaId: thumbMediaId
          hqmusicURL: hqmusicURL
          musicURL: musicURL
          description: description
          title: title
        fromUser: fromUser
        text:
          content: content
        video:
          thumbMediaURL: thumbMediaURL
          thumbMediaId: thumbMediaId
          mediaURL: mediaURL
          description: description
          mediaId: mediaId
          title: title
        articles:
          picURL: picURL
          description: description
          title: title
          URL: URL
      properties:
        fromUser:
          description: 发送人(运营号Id)
          type: string
        toUser:
          description: 接收用户openid
          type: string
        msgType:
          description: 消息类型:text 文本,image 图片,video 视频,voice 音频,music 音乐,articles 新闻
          type: string
        text:
          $ref: '#/components/schemas/TextMessage'
        image:
          $ref: '#/components/schemas/ImageMessage'
        voice:
          $ref: '#/components/schemas/VoiceMessage'
        video:
          $ref: '#/components/schemas/VideoMessage'
        music:
          $ref: '#/components/schemas/MusicMessage'
        articles:
          $ref: '#/components/schemas/ArticlesMessage'
      type: object
    ListUserReq:
      example:
        id: id
      properties:
        id:
          description: 公众号id
          type: string
      type: object
    UserDetailReq:
      example:
        openid: openid
        id: id
      properties:
        id:
          description: 公众号id
          type: string
        openid:
          description: 用户openid
          type: string
      type: object
    UpdateUserTagReq:
      example:
        openid: openid
        id: id
        tags:
        - tags
        - tags
      properties:
        id:
          description: 公众号id
          type: string
        openid:
          description: 用户openid
          type: string
        tags:
          description: 标签列表
          items:
            type: string
          type: array
      type: object
    UpdateUserRemarkReq:
      example:
        openid: openid
        remark: remark
        id: id
      properties:
        id:
          description: 公众号id
          type: string
        openid:
          description: 用户openid
          type: string
        remark:
          description: 备注
          type: string
      type: object
    User:
      example:
        country: country
        unionid: unionid
        qrScene: 9
        qrSceneStr: qrSceneStr
        subscribeTime: 5
        subscribe: 6
        city: city
        openid: openid
        sex: 1
        groupid: 5
        language: language
        remark: remark
        tagList:
        - name: name
          id: 7
        - name: name
          id: 7
        province: province
        nickname: nickname
        headimgurl: headimgurl
        subscribeScene: subscribeScene
        tagIdList:
        - 2
        - 2
      properties:
        subscribe:
          description: 用户是否订阅该公众号标识，值为0时，代表此用户没有关注该公众号，拉取不到其余信息。
          format: int32
          type: integer
        openid:
          description: 用户的标识，对当前公众号唯一
          type: string
        nickname:
          description: 用户的昵称
          type: string
        sex:
          description: 用户的性别，值为1时是男性，值为2时是女性，值为0时是未知
          format: int32
          type: integer
        language:
          description: 用户的语言，简体中文为zh_CN
          type: string
        city:
          description: 用户所在城市
          type: string
        province:
          description: 用户所在省份
          type: string
        country:
          description: 用户所在国家
          type: string
        headimgurl:
          description: 用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效
          type: string
        subscribeTime:
          description: 用户关注时间，为时间戳。如果用户曾多次关注，则取最后关注时间
          format: int64
          type: integer
        unionid:
          description: 只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段。
          type: string
        remark:
          description: 公众号运营者对粉丝的备注，公众号运营者可在微信公众平台用户管理界面对粉丝添加备注
          type: string
        groupid:
          description: 用户所在的分组ID（兼容旧的用户分组接口）
          format: int64
          type: integer
        tagIdList:
          items:
            format: int64
            type: integer
          type: array
        tagList:
          description: 用户被打上的标签ID列表
          items:
            $ref: '#/components/schemas/UserTag'
          type: array
        subscribeScene:
          description: ADD_SCENE_QR_CODE 扫描二维码，ADD_SCENE_PROFILE_LINK 图文页内名称点击，ADD_SCENE_PROFILE_ITEM图文页右上角菜单，ADD_SCENE_PAID
            支付后关注，ADD_SCENE_WECHAT_ADVERTISEMENT 微信广告，ADD_SCENE_OTHERS 其他
          type: string
        qrScene:
          description: 二维码扫码场景（开发者自定义）
          format: int64
          type: integer
        qrSceneStr:
          description: 二维码扫码场景描述（开发者自定义）
          type: string
      type: object
    UserTag:
      description: 用户标签
      example:
        name: name
        id: 7
      properties:
        id:
          description: 公众平台标签id
          format: int64
          type: integer
        name:
          description: 标签名称
          type: string
      type: object
    TextMessage:
      description: 文本消息
      example:
        content: content
      properties:
        content:
          description: 文本内容
          type: string
      type: object
    ImageMessage:
      description: 图片消息
      example:
        mediaURL: mediaURL
        mediaId: mediaId
      properties:
        mediaId:
          type: string
        mediaURL:
          description: 图片链接
          type: string
      type: object
    VoiceMessage:
      description: 语音消息
      example:
        mediaURL: mediaURL
        mediaId: mediaId
      properties:
        mediaId:
          type: string
        mediaURL:
          description: 音频链接
          type: string
      type: object
    VideoMessage:
      description: 视频消息
      example:
        thumbMediaURL: thumbMediaURL
        thumbMediaId: thumbMediaId
        mediaURL: mediaURL
        description: description
        mediaId: mediaId
        title: title
      properties:
        mediaId:
          type: string
        thumbMediaId:
          type: string
        mediaURL:
          description: 视频链接
          type: string
        thumbMediaURL:
          description: 视频封面图片链接
          type: string
        title:
          description: 视频标题
          type: string
        description:
          description: 视频描述
          type: string
      type: object
    MusicMessage:
      description: 音乐消息
      example:
        thumbMediaURL: thumbMediaURL
        thumbMediaId: thumbMediaId
        hqmusicURL: hqmusicURL
        musicURL: musicURL
        description: description
        title: title
      properties:
        title:
          description: 音乐标题
          type: string
        description:
          description: 音乐描述
          type: string
        musicURL:
          description: 音乐链接
          type: string
        hqmusicURL:
          description: 高品质音乐链接，wifi环境优先使用该链接播放音乐
          type: string
        thumbMediaId:
          type: string
        thumbMediaURL:
          description: 音乐图片链接
          type: string
      type: object
    ArticlesMessage:
      description: 图文消息
      example:
        picURL: picURL
        description: description
        title: title
        URL: URL
      properties:
        title:
          description: 标题
          type: string
        description:
          description: 描述
          type: string
        URL:
          description: 链接
          type: string
        picURL:
          description: 图片链接
          type: string
      type: object
    TextMessageEvent:
      description: 文本消息事件
      properties:
        toUserName:
          description: 开发者微信号
          type: string
        fromUserName:
          description: 发送方微信号，若为普通用户，则是一个OpenID
          type: string
        createTime:
          format: int64
          type: integer
        content:
          type: string
        msgType:
          type: string
        msgId:
          description: 消息id
          format: int64
          type: integer
      type: object
    ImageMessageEvent:
      description: 图片消息事件
      properties:
        toUserName:
          type: string
        fromUserName:
          type: string
        createTime:
          format: int64
          type: integer
        msgType:
          type: string
        msgId:
          format: int64
          type: integer
        picUrl:
          type: string
        mediaId:
          type: string
        mediaURL:
          type: string
      type: object
    VoiceMessageEvent:
      description: 语音消息事件
      properties:
        toUserName:
          type: string
        fromUserName:
          type: string
        createTime:
          format: int64
          type: integer
        msgType:
          type: string
        msgId:
          format: int64
          type: integer
        format:
          type: string
        mediaId:
          type: string
        mediaURL:
          type: string
        recognition:
          type: string
      type: object
    VideoMessageEvent:
      description: 视频消息事件
      properties:
        toUserName:
          type: string
        fromUserName:
          type: string
        createTime:
          format: int64
          type: integer
        msgType:
          type: string
        msgId:
          format: int64
          type: integer
        mediaId:
          type: string
        mediaURL:
          type: string
        thumbMediaURL:
          type: string
        thumbMediaId:
          type: string
      type: object
    ShortVideoMessageEvent:
      description: 小视频消息事件
      properties:
        toUserName:
          type: string
        fromUserName:
          type: string
        createTime:
          format: int64
          type: integer
        msgType:
          type: string
        msgId:
          format: int64
          type: integer
        mediaId:
          type: string
        mediaURL:
          type: string
        thumbMediaURL:
          type: string
        thumbMediaId:
          type: string
      type: object
    LocationMessageEvent:
      description: 地理位置消息事件
      properties:
        toUserName:
          type: string
        fromUserName:
          type: string
        createTime:
          format: int64
          type: integer
        msgType:
          type: string
        msgId:
          format: int64
          type: integer
        locationX:
          format: double
          type: number
        locationY:
          format: double
          type: number
        scale:
          type: integer
        label:
          type: string
      type: object
    LinkMessageEvent:
      description: 链接消息事件
      properties:
        toUserName:
          type: string
        fromUserName:
          type: string
        createTime:
          format: int64
          type: integer
        msgType:
          type: string
        msgId:
          format: int64
          type: integer
        title:
          type: string
        description:
          type: string
        url:
          type: string
      type: object
    EventsEvent:
      description: 链接消息事件
      properties:
        toUserName:
          type: string
        fromUserName:
          type: string
        createTime:
          format: int64
          type: integer
        msgType:
          type: string
        event:
          type: string
        eventKey:
          type: string
        ticket:
          type: string
        latitude:
          format: double
          type: number
        longitude:
          format: double
          type: number
        precision:
          format: double
          type: number
      type: object
    APIResponse:
      example:
        msg: msg
        code: 0
        data: '{}'
      properties:
        code:
          format: int32
          type: integer
        msg:
          type: string
        data:
          properties: {}
          type: object
      type: object
    inline_response_200:
      example:
        msg: msg
        code: 0
        data:
        - country: country
          unionid: unionid
          qrScene: 9
          qrSceneStr: qrSceneStr
          subscribeTime: 5
          subscribe: 6
          city: city
          openid: openid
          sex: 1
          groupid: 5
          language: language
          remark: remark
          tagList:
          - name: name
            id: 7
          - name: name
            id: 7
          province: province
          nickname: nickname
          headimgurl: headimgurl
          subscribeScene: subscribeScene
          tagIdList:
          - 2
          - 2
        - country: country
          unionid: unionid
          qrScene: 9
          qrSceneStr: qrSceneStr
          subscribeTime: 5
          subscribe: 6
          city: city
          openid: openid
          sex: 1
          groupid: 5
          language: language
          remark: remark
          tagList:
          - name: name
            id: 7
          - name: name
            id: 7
          province: province
          nickname: nickname
          headimgurl: headimgurl
          subscribeScene: subscribeScene
          tagIdList:
          - 2
          - 2
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          items:
            $ref: '#/components/schemas/User'
          type: array
    inline_response_200_1:
      example:
        msg: msg
        code: 0
        data:
          country: country
          unionid: unionid
          qrScene: 9
          qrSceneStr: qrSceneStr
          subscribeTime: 5
          subscribe: 6
          city: city
          openid: openid
          sex: 1
          groupid: 5
          language: language
          remark: remark
          tagList:
          - name: name
            id: 7
          - name: name
            id: 7
          province: province
          nickname: nickname
          headimgurl: headimgurl
          subscribeScene: subscribeScene
          tagIdList:
          - 2
          - 2
      properties:
        code:
          type: integer
        msg:
          type: string
        data:
          $ref: '#/components/schemas/User'
